engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: false
  scss-lint:
    enabled: true
  coffeelint:
    enabled: true
  eslint:
    enabled: true
ratings:
  paths:
  - app/**
  - assets/**
exclude_paths:
  - test/**
  - doc/**
  - config/**
  - assets/jspm_packages/**
  - public/**
  - vender/**
